// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Discuss: typeof import('./src/components/Discuss/index.vue')['default']
    Editor: typeof import('./src/components/Discuss/Editor.vue')['default']
    Emotion: typeof import('./src/components/Emotion/index.vue')['default']
    Item: typeof import('./src/components/Discuss/Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
